apiVersion: apps/v1
kind: Deployment
metadata:
  name: priority-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: priority-api
  template:
    metadata:
      labels:
        app: priority-api
    spec:
      containers:
        - name: priority-api
          image: priority-api:v5
          imagePullPolicy: Never
          ports:
            - name: http          # nome da porta do container (opcional, mas organizado)
              containerPort: 8080
          env:
            # ===========================
            # Configuração geral do Q1/Q2/Q3
            # ===========================
            - name: N_PROCESSES
              value: "3"

            # ===========================
            # Modo de atraso (hardcore mode)
            # ===========================
            # "off" -> comportamento normal
            # "on"  -> atrasa ACKs no pod, de acordo com as variáveis abaixo
            - name: DELAY_MODE
              value: "off"        # mude para "on" para testar atraso real no pod

            # Processo cujo ACK será atrasado quando DELAY_MODE="on"
            - name: DELAYED_PROCESS_ID
              value: "2"

            # Mensagem alvo:
            # - ""      -> atrasa QUALQUER msg desse processo
            # - "P1-10" -> atrasa só essa mensagem específica
            - name: DELAYED_MSG_ID
              value: ""

            # Quantos segundos o ACK ficará atrasado nesse pod
            - name: DELAY_SECONDS
              value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: priority-api-svc
spec:
  selector:
    app: priority-api
  ports:
    - name: http          # <- ESSA linha é obrigatória para a validação atual
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
