apiVersion: v1
kind: Service
metadata:
  name: algoritmos-coordenacao-service
spec:
  clusterIP: None 
  selector:
    app: algoritmos-coordenacao
  ports:
    - name: http
      port: 8080
      targetPort: 8080
